### ISSUE TITLE
Support Table

### ISSUE THREAD

**Issue by muratsplat** [showdownjs/github-extension#1]
Hi,

The extension supports table ? 

like this:

| Type | Elements |
| --- | --- |
| Headings | `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `h7`, `h8` |
| Prose | `p`, `div`, `blockquote` |
| Formatted | `pre` |
| Inline | `b`, `i`, `strong`, `em`, `tt`, `code`, `ins`, `del`, `sup`, `sub`, `kbd`, `samp`, `q`, `var` |
| Lists | `ol`, `ul`, `li`, `dl`, `dt`, `dd` |
| Tables | `table`, `thead`, `tbody`, `tfoot`, `tr`, `td`, `th` |
| Breaks | `br`, `hr` |
| Ruby (East Asian) | `ruby`, `rt`, `rp` |

**Comment by muratsplat** [comment]
Anyway I think that Marked supports full github flavored markdown : https://github.com/chjj/marked

**Comment by pdeschen** [comment]
There's the table extension for table support.

I think it could be a nice addition to have extension uses other extensions. 

Pascal

**Comment by tivie** [comment]
> I think it could be a nice addition to have extension uses other extensions.

Yeah, that would be nice. It would require us to change the extension mechanism a bit. For now, we can add the table-extension as a dependency in package.json and bower.json.

**Comment by tivie** [comment]
Github flavor is now bundled with core.

I you want to activate it, you can do the following:

``` js
showdown.setFlavor('github');
// or
var conv = new showdown.Converter().setFlavor('github');
```
