### ISSUE TITLE
Support for use on server.

### ISSUE THREAD

**Issue by crestenstclair** [showdownjs/github-extension#3]
How would one use this on the server? Using the:

`<script ...`

method is not an option.

Attempting to  require it throws a file not found exception.

**Comment by pdeschen** [comment]
Have a look at the [showdown wiki](https://github.com/showdownjs/showdown/wiki/extensions#server-side-extension-usage)

**Comment by crestenstclair** [comment]
Yeah, I wasn't clear enough on this. I don't actually want it to work on the server, I want it to work with webpack. Rewriting issue.

**Comment by tivie** [comment]
What version of showdown are you using? From 1.2.0 and onward, github extension is bundled with core. You can check the [options section in showdown docs](http://github.com/showdownjs/showdown) for more info
