### ISSUE TITLE
Use with webpack / browserify?

### ISSUE THREAD

**Issue by crestenstclair** [showdownjs/github-extension#4]
Is there a quick way to get this extension to work with webpack?

Currently I'm getting the following error:

```
Uncaught Error: Extension "github" could not be loaded. It was either not found or is not a valid extension.
```

**Comment by tivie** [comment]
Please note that if you're using showdown v1.2.0 or greater, github extension comes bundled with it. So to activate it, you do this:

``` js
showdown.setFlavor('github');
// or
var conv = new showdown.Converter().setFlavor('github');
```

---

If you still want to use the github extension, you would do the following:
1. run this on bash/cmd:
   
   ``` bash
   npm install showdown-github --save
   ```
2. add this to your main.js (or index,js):
   
   ``` js
   require('showdown-github');
   ```
3. then load the extension:
   
   ``` js
   var conv = new showdown.Converter({extensions: ['github']});
   ```

**Comment by tivie** [comment]
Closing issue as there were no developments
