### ISSUE TITLE
Old Extension warning

### ISSUE THREAD

**Issue by rahmanda** [showdownjs/github-extension#6]
Console raise this warning :

> DEPRECATION WARNING: github is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!  

Is there a way to turn it off ?

**Comment by tivie** [comment]
Github extension was merged in main showdown so is no longer needed.

You can get the same functionality by activating the preset "github" in showdown.

Please refer to showdown main repo documentation for more information.

**Comment by rahmanda** [comment]
My bad, i didn't read the documentation properly. Thanks @tivie :+1:
